/*
Public Clouds

> The base URL for this API is: **https://api.leaseweb.com/publicCloud/v1/_**  This API provides ways to launch and manage Public Cloud instances.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publiccloud

import (
	"encoding/json"
	"fmt"
)

// checks if the SecurityGroupList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecurityGroupList{}

// SecurityGroupList struct for SecurityGroupList
type SecurityGroupList struct {
	SecurityGroups []SecurityGroup `json:"securityGroups"`
	Metadata Metadata `json:"_metadata"`
	AdditionalProperties map[string]interface{}
}

type _SecurityGroupList SecurityGroupList

// NewSecurityGroupList instantiates a new SecurityGroupList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecurityGroupList(securityGroups []SecurityGroup, metadata Metadata) *SecurityGroupList {
	this := SecurityGroupList{}
	this.SecurityGroups = securityGroups
	this.Metadata = metadata
	return &this
}

// NewSecurityGroupListWithDefaults instantiates a new SecurityGroupList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecurityGroupListWithDefaults() *SecurityGroupList {
	this := SecurityGroupList{}
	return &this
}

// GetSecurityGroups returns the SecurityGroups field value
func (o *SecurityGroupList) GetSecurityGroups() []SecurityGroup {
	if o == nil {
		var ret []SecurityGroup
		return ret
	}

	return o.SecurityGroups
}

// GetSecurityGroupsOk returns a tuple with the SecurityGroups field value
// and a boolean to check if the value has been set.
func (o *SecurityGroupList) GetSecurityGroupsOk() ([]SecurityGroup, bool) {
	if o == nil {
		return nil, false
	}
	return o.SecurityGroups, true
}

// SetSecurityGroups sets field value
func (o *SecurityGroupList) SetSecurityGroups(v []SecurityGroup) {
	o.SecurityGroups = v
}

// GetMetadata returns the Metadata field value
func (o *SecurityGroupList) GetMetadata() Metadata {
	if o == nil {
		var ret Metadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *SecurityGroupList) GetMetadataOk() (*Metadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *SecurityGroupList) SetMetadata(v Metadata) {
	o.Metadata = v
}

func (o SecurityGroupList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecurityGroupList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["securityGroups"] = o.SecurityGroups
	toSerialize["_metadata"] = o.Metadata

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SecurityGroupList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"securityGroups",
		"_metadata",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecurityGroupList := _SecurityGroupList{}

	err = json.Unmarshal(data, &varSecurityGroupList)

	if err != nil {
		return err
	}

	*o = SecurityGroupList(varSecurityGroupList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "securityGroups")
		delete(additionalProperties, "_metadata")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSecurityGroupList struct {
	value *SecurityGroupList
	isSet bool
}

func (v NullableSecurityGroupList) Get() *SecurityGroupList {
	return v.value
}

func (v *NullableSecurityGroupList) Set(val *SecurityGroupList) {
	v.value = val
	v.isSet = true
}

func (v NullableSecurityGroupList) IsSet() bool {
	return v.isSet
}

func (v *NullableSecurityGroupList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecurityGroupList(val *SecurityGroupList) *NullableSecurityGroupList {
	return &NullableSecurityGroupList{value: val, isSet: true}
}

func (v NullableSecurityGroupList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecurityGroupList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


