/*
Public Clouds

> The base URL for this API is: **https://api.leaseweb.com/publicCloud/v1/_**  This API provides ways to launch and manage Public Cloud instances.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publiccloud

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateSecurityGroupOpts type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateSecurityGroupOpts{}

// UpdateSecurityGroupOpts struct for UpdateSecurityGroupOpts
type UpdateSecurityGroupOpts struct {
	// The name of the security group
	Name string `json:"name"`
	AdditionalProperties map[string]interface{}
}

type _UpdateSecurityGroupOpts UpdateSecurityGroupOpts

// NewUpdateSecurityGroupOpts instantiates a new UpdateSecurityGroupOpts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSecurityGroupOpts(name string) *UpdateSecurityGroupOpts {
	this := UpdateSecurityGroupOpts{}
	this.Name = name
	return &this
}

// NewUpdateSecurityGroupOptsWithDefaults instantiates a new UpdateSecurityGroupOpts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSecurityGroupOptsWithDefaults() *UpdateSecurityGroupOpts {
	this := UpdateSecurityGroupOpts{}
	return &this
}

// GetName returns the Name field value
func (o *UpdateSecurityGroupOpts) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdateSecurityGroupOpts) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdateSecurityGroupOpts) SetName(v string) {
	o.Name = v
}

func (o UpdateSecurityGroupOpts) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateSecurityGroupOpts) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateSecurityGroupOpts) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateSecurityGroupOpts := _UpdateSecurityGroupOpts{}

	err = json.Unmarshal(data, &varUpdateSecurityGroupOpts)

	if err != nil {
		return err
	}

	*o = UpdateSecurityGroupOpts(varUpdateSecurityGroupOpts)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateSecurityGroupOpts struct {
	value *UpdateSecurityGroupOpts
	isSet bool
}

func (v NullableUpdateSecurityGroupOpts) Get() *UpdateSecurityGroupOpts {
	return v.value
}

func (v *NullableUpdateSecurityGroupOpts) Set(val *UpdateSecurityGroupOpts) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSecurityGroupOpts) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSecurityGroupOpts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSecurityGroupOpts(val *UpdateSecurityGroupOpts) *NullableUpdateSecurityGroupOpts {
	return &NullableUpdateSecurityGroupOpts{value: val, isSet: true}
}

func (v NullableUpdateSecurityGroupOpts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSecurityGroupOpts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


