/*
Public Clouds

> The base URL for this API is: **https://api.leaseweb.com/publicCloud/v1/_**  This API provides ways to launch and manage Public Cloud instances.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publiccloud

import (
	"encoding/json"
)

// checks if the MetricsPropertiesBase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetricsPropertiesBase{}

// MetricsPropertiesBase struct for MetricsPropertiesBase
type MetricsPropertiesBase struct {
	Values []MetricsValues `json:"values,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MetricsPropertiesBase MetricsPropertiesBase

// NewMetricsPropertiesBase instantiates a new MetricsPropertiesBase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetricsPropertiesBase() *MetricsPropertiesBase {
	this := MetricsPropertiesBase{}
	return &this
}

// NewMetricsPropertiesBaseWithDefaults instantiates a new MetricsPropertiesBase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetricsPropertiesBaseWithDefaults() *MetricsPropertiesBase {
	this := MetricsPropertiesBase{}
	return &this
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *MetricsPropertiesBase) GetValues() []MetricsValues {
	if o == nil || IsNil(o.Values) {
		var ret []MetricsValues
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsPropertiesBase) GetValuesOk() ([]MetricsValues, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *MetricsPropertiesBase) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []MetricsValues and assigns it to the Values field.
func (o *MetricsPropertiesBase) SetValues(v []MetricsValues) {
	o.Values = v
}

func (o MetricsPropertiesBase) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetricsPropertiesBase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MetricsPropertiesBase) UnmarshalJSON(data []byte) (err error) {
	varMetricsPropertiesBase := _MetricsPropertiesBase{}

	err = json.Unmarshal(data, &varMetricsPropertiesBase)

	if err != nil {
		return err
	}

	*o = MetricsPropertiesBase(varMetricsPropertiesBase)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "values")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMetricsPropertiesBase struct {
	value *MetricsPropertiesBase
	isSet bool
}

func (v NullableMetricsPropertiesBase) Get() *MetricsPropertiesBase {
	return v.value
}

func (v *NullableMetricsPropertiesBase) Set(val *MetricsPropertiesBase) {
	v.value = val
	v.isSet = true
}

func (v NullableMetricsPropertiesBase) IsSet() bool {
	return v.isSet
}

func (v *NullableMetricsPropertiesBase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetricsPropertiesBase(val *MetricsPropertiesBase) *NullableMetricsPropertiesBase {
	return &NullableMetricsPropertiesBase{value: val, isSet: true}
}

func (v NullableMetricsPropertiesBase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetricsPropertiesBase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


