/*
LeaseWeb API for launching and managing Public Cloud instances

> The base URL for this API is: **https://api.leaseweb.com/publicCloud/v1/_**  This API provides ways to launch and manage Public Cloud instances.  <div class=\"badge\">BETA</div> This API is in BETA. Documentation might be incorrect or incomplete. Functionality might change with the final release.>

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publiccloud

import (
	"encoding/json"
	"time"
)

// checks if the CpuMetricsMetadataSummaryPeak type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CpuMetricsMetadataSummaryPeak{}

// CpuMetricsMetadataSummaryPeak struct for CpuMetricsMetadataSummaryPeak
type CpuMetricsMetadataSummaryPeak struct {
	// The highest CPU usage given the provided aggregation and granularity
	Value *string `json:"value,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CpuMetricsMetadataSummaryPeak CpuMetricsMetadataSummaryPeak

// NewCpuMetricsMetadataSummaryPeak instantiates a new CpuMetricsMetadataSummaryPeak object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCpuMetricsMetadataSummaryPeak() *CpuMetricsMetadataSummaryPeak {
	this := CpuMetricsMetadataSummaryPeak{}
	return &this
}

// NewCpuMetricsMetadataSummaryPeakWithDefaults instantiates a new CpuMetricsMetadataSummaryPeak object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCpuMetricsMetadataSummaryPeakWithDefaults() *CpuMetricsMetadataSummaryPeak {
	this := CpuMetricsMetadataSummaryPeak{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *CpuMetricsMetadataSummaryPeak) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CpuMetricsMetadataSummaryPeak) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CpuMetricsMetadataSummaryPeak) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *CpuMetricsMetadataSummaryPeak) SetValue(v string) {
	o.Value = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *CpuMetricsMetadataSummaryPeak) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CpuMetricsMetadataSummaryPeak) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *CpuMetricsMetadataSummaryPeak) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *CpuMetricsMetadataSummaryPeak) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

func (o CpuMetricsMetadataSummaryPeak) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CpuMetricsMetadataSummaryPeak) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CpuMetricsMetadataSummaryPeak) UnmarshalJSON(data []byte) (err error) {
	varCpuMetricsMetadataSummaryPeak := _CpuMetricsMetadataSummaryPeak{}

	err = json.Unmarshal(data, &varCpuMetricsMetadataSummaryPeak)

	if err != nil {
		return err
	}

	*o = CpuMetricsMetadataSummaryPeak(varCpuMetricsMetadataSummaryPeak)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "value")
		delete(additionalProperties, "timestamp")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCpuMetricsMetadataSummaryPeak struct {
	value *CpuMetricsMetadataSummaryPeak
	isSet bool
}

func (v NullableCpuMetricsMetadataSummaryPeak) Get() *CpuMetricsMetadataSummaryPeak {
	return v.value
}

func (v *NullableCpuMetricsMetadataSummaryPeak) Set(val *CpuMetricsMetadataSummaryPeak) {
	v.value = val
	v.isSet = true
}

func (v NullableCpuMetricsMetadataSummaryPeak) IsSet() bool {
	return v.isSet
}

func (v *NullableCpuMetricsMetadataSummaryPeak) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCpuMetricsMetadataSummaryPeak(val *CpuMetricsMetadataSummaryPeak) *NullableCpuMetricsMetadataSummaryPeak {
	return &NullableCpuMetricsMetadataSummaryPeak{value: val, isSet: true}
}

func (v NullableCpuMetricsMetadataSummaryPeak) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCpuMetricsMetadataSummaryPeak) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


