/*
Public Clouds

> The base URL for this API is: **https://api.leaseweb.com/publicCloud/v1/_**  This API provides ways to launch and manage Public Cloud instances.  <div class=\"badge\">BETA</div> This API is in BETA. Documentation might be incorrect or incomplete. Functionality might change with the final release.>

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publiccloud

import (
	"encoding/json"
)

// checks if the DataTransferredMetrics1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataTransferredMetrics1{}

// DataTransferredMetrics1 struct for DataTransferredMetrics1
type DataTransferredMetrics1 struct {
	DataIn *MetricsPropertiesRequests `json:"dataIn,omitempty"`
	DataOut *MetricsPropertiesRequests `json:"dataOut,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DataTransferredMetrics1 DataTransferredMetrics1

// NewDataTransferredMetrics1 instantiates a new DataTransferredMetrics1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataTransferredMetrics1() *DataTransferredMetrics1 {
	this := DataTransferredMetrics1{}
	return &this
}

// NewDataTransferredMetrics1WithDefaults instantiates a new DataTransferredMetrics1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataTransferredMetrics1WithDefaults() *DataTransferredMetrics1 {
	this := DataTransferredMetrics1{}
	return &this
}

// GetDataIn returns the DataIn field value if set, zero value otherwise.
func (o *DataTransferredMetrics1) GetDataIn() MetricsPropertiesRequests {
	if o == nil || IsNil(o.DataIn) {
		var ret MetricsPropertiesRequests
		return ret
	}
	return *o.DataIn
}

// GetDataInOk returns a tuple with the DataIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataTransferredMetrics1) GetDataInOk() (*MetricsPropertiesRequests, bool) {
	if o == nil || IsNil(o.DataIn) {
		return nil, false
	}
	return o.DataIn, true
}

// HasDataIn returns a boolean if a field has been set.
func (o *DataTransferredMetrics1) HasDataIn() bool {
	if o != nil && !IsNil(o.DataIn) {
		return true
	}

	return false
}

// SetDataIn gets a reference to the given MetricsPropertiesRequests and assigns it to the DataIn field.
func (o *DataTransferredMetrics1) SetDataIn(v MetricsPropertiesRequests) {
	o.DataIn = &v
}

// GetDataOut returns the DataOut field value if set, zero value otherwise.
func (o *DataTransferredMetrics1) GetDataOut() MetricsPropertiesRequests {
	if o == nil || IsNil(o.DataOut) {
		var ret MetricsPropertiesRequests
		return ret
	}
	return *o.DataOut
}

// GetDataOutOk returns a tuple with the DataOut field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataTransferredMetrics1) GetDataOutOk() (*MetricsPropertiesRequests, bool) {
	if o == nil || IsNil(o.DataOut) {
		return nil, false
	}
	return o.DataOut, true
}

// HasDataOut returns a boolean if a field has been set.
func (o *DataTransferredMetrics1) HasDataOut() bool {
	if o != nil && !IsNil(o.DataOut) {
		return true
	}

	return false
}

// SetDataOut gets a reference to the given MetricsPropertiesRequests and assigns it to the DataOut field.
func (o *DataTransferredMetrics1) SetDataOut(v MetricsPropertiesRequests) {
	o.DataOut = &v
}

func (o DataTransferredMetrics1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataTransferredMetrics1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DataIn) {
		toSerialize["dataIn"] = o.DataIn
	}
	if !IsNil(o.DataOut) {
		toSerialize["dataOut"] = o.DataOut
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DataTransferredMetrics1) UnmarshalJSON(data []byte) (err error) {
	varDataTransferredMetrics1 := _DataTransferredMetrics1{}

	err = json.Unmarshal(data, &varDataTransferredMetrics1)

	if err != nil {
		return err
	}

	*o = DataTransferredMetrics1(varDataTransferredMetrics1)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "dataIn")
		delete(additionalProperties, "dataOut")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDataTransferredMetrics1 struct {
	value *DataTransferredMetrics1
	isSet bool
}

func (v NullableDataTransferredMetrics1) Get() *DataTransferredMetrics1 {
	return v.value
}

func (v *NullableDataTransferredMetrics1) Set(val *DataTransferredMetrics1) {
	v.value = val
	v.isSet = true
}

func (v NullableDataTransferredMetrics1) IsSet() bool {
	return v.isSet
}

func (v *NullableDataTransferredMetrics1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataTransferredMetrics1(val *DataTransferredMetrics1) *NullableDataTransferredMetrics1 {
	return &NullableDataTransferredMetrics1{value: val, isSet: true}
}

func (v NullableDataTransferredMetrics1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataTransferredMetrics1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


