/*
LeaseWeb API for launching and managing Public Cloud instances

> The base URL for this API is: **https://api.leaseweb.com/publicCloud/v1/_**  This API provides ways to launch and manage Public Cloud instances.  <div class=\"badge\">BETA</div> This API is in BETA. Documentation might be incorrect or incomplete. Functionality might change with the final release.>

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package publiccloud

import (
	"encoding/json"
	"fmt"
)

// checks if the StoreCredentialOpts type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoreCredentialOpts{}

// StoreCredentialOpts struct for StoreCredentialOpts
type StoreCredentialOpts struct {
	Type CredentialType `json:"type"`
	// Can contain only alphanumeric values and characters `@`, `.`, `-` and `_`
	Username string `json:"username"`
	// The password you'd like to store
	Password string `json:"password"`
	AdditionalProperties map[string]interface{}
}

type _StoreCredentialOpts StoreCredentialOpts

// NewStoreCredentialOpts instantiates a new StoreCredentialOpts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoreCredentialOpts(type_ CredentialType, username string, password string) *StoreCredentialOpts {
	this := StoreCredentialOpts{}
	this.Type = type_
	this.Username = username
	this.Password = password
	return &this
}

// NewStoreCredentialOptsWithDefaults instantiates a new StoreCredentialOpts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoreCredentialOptsWithDefaults() *StoreCredentialOpts {
	this := StoreCredentialOpts{}
	return &this
}

// GetType returns the Type field value
func (o *StoreCredentialOpts) GetType() CredentialType {
	if o == nil {
		var ret CredentialType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *StoreCredentialOpts) GetTypeOk() (*CredentialType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *StoreCredentialOpts) SetType(v CredentialType) {
	o.Type = v
}

// GetUsername returns the Username field value
func (o *StoreCredentialOpts) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *StoreCredentialOpts) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *StoreCredentialOpts) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *StoreCredentialOpts) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *StoreCredentialOpts) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *StoreCredentialOpts) SetPassword(v string) {
	o.Password = v
}

func (o StoreCredentialOpts) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StoreCredentialOpts) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["username"] = o.Username
	toSerialize["password"] = o.Password

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StoreCredentialOpts) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"username",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStoreCredentialOpts := _StoreCredentialOpts{}

	err = json.Unmarshal(data, &varStoreCredentialOpts)

	if err != nil {
		return err
	}

	*o = StoreCredentialOpts(varStoreCredentialOpts)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "username")
		delete(additionalProperties, "password")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStoreCredentialOpts struct {
	value *StoreCredentialOpts
	isSet bool
}

func (v NullableStoreCredentialOpts) Get() *StoreCredentialOpts {
	return v.value
}

func (v *NullableStoreCredentialOpts) Set(val *StoreCredentialOpts) {
	v.value = val
	v.isSet = true
}

func (v NullableStoreCredentialOpts) IsSet() bool {
	return v.isSet
}

func (v *NullableStoreCredentialOpts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoreCredentialOpts(val *StoreCredentialOpts) *NullableStoreCredentialOpts {
	return &NullableStoreCredentialOpts{value: val, isSet: true}
}

func (v NullableStoreCredentialOpts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoreCredentialOpts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


