/*
Ordering

This document outlines the ordering API. The API is only available for customers with invoice payment method.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ordering

import (
	"encoding/json"
)

// checks if the DedicatedServer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DedicatedServer{}

// DedicatedServer struct for DedicatedServer
type DedicatedServer struct {
	// Id of the server
	Id *string `json:"id,omitempty"`
	// Name of the server
	Name *string `json:"name,omitempty"`
	// Chassis of the server
	Chassis *string `json:"chassis,omitempty"`
	Cpu *Cpu `json:"cpu,omitempty"`
	// Time to get the server ready
	DeliveryMethod *string `json:"deliveryMethod,omitempty"`
	// HDD info of the server
	Hdd []Hdd `json:"hdd,omitempty"`
	Ram *Ram `json:"ram,omitempty"`
	// Location of the server
	Location []string `json:"location,omitempty"`
	// Selected operating system
	OperatingSystem *string `json:"operatingSystem,omitempty"`
	// Disk set where the OS is installed
	InstallOsOnHdd *string `json:"installOsOnHdd,omitempty"`
	// Selected control panel
	ControlPanel *string `json:"controlPanel,omitempty"`
	// IP connectivity type
	IpConnectivityType *string `json:"ipConnectivityType,omitempty"`
	// Data pack configuration
	DataPackConfiguration *string `json:"dataPackConfiguration,omitempty"`
	// Uplink port speed
	UplinkPortSpeed *string `json:"uplinkPortSpeed,omitempty"`
	// Private network configuration
	PrivateNetwork1xvlan *string `json:"privateNetwork1xvlan,omitempty"`
	// IPv4 configuration
	IpV4Configuration *string `json:"ipV4Configuration,omitempty"`
	// Additional services
	AdditionalServices []string `json:"additionalServices,omitempty"`
	// Monitoring type
	MonitoringType *string `json:"monitoringType,omitempty"`
	// DDoS IP protection
	DdosIpProtection *string `json:"ddosIpProtection,omitempty"`
	// Service level agreement
	ServiceLevelAgreement *string `json:"serviceLevelAgreement,omitempty"`
	ConfigurationOptions *DedicatedServerConfigurationOptions1 `json:"configurationOptions,omitempty"`
	Price *ProductPricePrice `json:"price,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DedicatedServer DedicatedServer

// NewDedicatedServer instantiates a new DedicatedServer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDedicatedServer() *DedicatedServer {
	this := DedicatedServer{}
	return &this
}

// NewDedicatedServerWithDefaults instantiates a new DedicatedServer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDedicatedServerWithDefaults() *DedicatedServer {
	this := DedicatedServer{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DedicatedServer) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedServer) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DedicatedServer) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DedicatedServer) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DedicatedServer) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedServer) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DedicatedServer) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DedicatedServer) SetName(v string) {
	o.Name = &v
}

// GetChassis returns the Chassis field value if set, zero value otherwise.
func (o *DedicatedServer) GetChassis() string {
	if o == nil || IsNil(o.Chassis) {
		var ret string
		return ret
	}
	return *o.Chassis
}

// GetChassisOk returns a tuple with the Chassis field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedServer) GetChassisOk() (*string, bool) {
	if o == nil || IsNil(o.Chassis) {
		return nil, false
	}
	return o.Chassis, true
}

// HasChassis returns a boolean if a field has been set.
func (o *DedicatedServer) HasChassis() bool {
	if o != nil && !IsNil(o.Chassis) {
		return true
	}

	return false
}

// SetChassis gets a reference to the given string and assigns it to the Chassis field.
func (o *DedicatedServer) SetChassis(v string) {
	o.Chassis = &v
}

// GetCpu returns the Cpu field value if set, zero value otherwise.
func (o *DedicatedServer) GetCpu() Cpu {
	if o == nil || IsNil(o.Cpu) {
		var ret Cpu
		return ret
	}
	return *o.Cpu
}

// GetCpuOk returns a tuple with the Cpu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedServer) GetCpuOk() (*Cpu, bool) {
	if o == nil || IsNil(o.Cpu) {
		return nil, false
	}
	return o.Cpu, true
}

// HasCpu returns a boolean if a field has been set.
func (o *DedicatedServer) HasCpu() bool {
	if o != nil && !IsNil(o.Cpu) {
		return true
	}

	return false
}

// SetCpu gets a reference to the given Cpu and assigns it to the Cpu field.
func (o *DedicatedServer) SetCpu(v Cpu) {
	o.Cpu = &v
}

// GetDeliveryMethod returns the DeliveryMethod field value if set, zero value otherwise.
func (o *DedicatedServer) GetDeliveryMethod() string {
	if o == nil || IsNil(o.DeliveryMethod) {
		var ret string
		return ret
	}
	return *o.DeliveryMethod
}

// GetDeliveryMethodOk returns a tuple with the DeliveryMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedServer) GetDeliveryMethodOk() (*string, bool) {
	if o == nil || IsNil(o.DeliveryMethod) {
		return nil, false
	}
	return o.DeliveryMethod, true
}

// HasDeliveryMethod returns a boolean if a field has been set.
func (o *DedicatedServer) HasDeliveryMethod() bool {
	if o != nil && !IsNil(o.DeliveryMethod) {
		return true
	}

	return false
}

// SetDeliveryMethod gets a reference to the given string and assigns it to the DeliveryMethod field.
func (o *DedicatedServer) SetDeliveryMethod(v string) {
	o.DeliveryMethod = &v
}

// GetHdd returns the Hdd field value if set, zero value otherwise.
func (o *DedicatedServer) GetHdd() []Hdd {
	if o == nil || IsNil(o.Hdd) {
		var ret []Hdd
		return ret
	}
	return o.Hdd
}

// GetHddOk returns a tuple with the Hdd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedServer) GetHddOk() ([]Hdd, bool) {
	if o == nil || IsNil(o.Hdd) {
		return nil, false
	}
	return o.Hdd, true
}

// HasHdd returns a boolean if a field has been set.
func (o *DedicatedServer) HasHdd() bool {
	if o != nil && !IsNil(o.Hdd) {
		return true
	}

	return false
}

// SetHdd gets a reference to the given []Hdd and assigns it to the Hdd field.
func (o *DedicatedServer) SetHdd(v []Hdd) {
	o.Hdd = v
}

// GetRam returns the Ram field value if set, zero value otherwise.
func (o *DedicatedServer) GetRam() Ram {
	if o == nil || IsNil(o.Ram) {
		var ret Ram
		return ret
	}
	return *o.Ram
}

// GetRamOk returns a tuple with the Ram field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedServer) GetRamOk() (*Ram, bool) {
	if o == nil || IsNil(o.Ram) {
		return nil, false
	}
	return o.Ram, true
}

// HasRam returns a boolean if a field has been set.
func (o *DedicatedServer) HasRam() bool {
	if o != nil && !IsNil(o.Ram) {
		return true
	}

	return false
}

// SetRam gets a reference to the given Ram and assigns it to the Ram field.
func (o *DedicatedServer) SetRam(v Ram) {
	o.Ram = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *DedicatedServer) GetLocation() []string {
	if o == nil || IsNil(o.Location) {
		var ret []string
		return ret
	}
	return o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedServer) GetLocationOk() ([]string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *DedicatedServer) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given []string and assigns it to the Location field.
func (o *DedicatedServer) SetLocation(v []string) {
	o.Location = v
}

// GetOperatingSystem returns the OperatingSystem field value if set, zero value otherwise.
func (o *DedicatedServer) GetOperatingSystem() string {
	if o == nil || IsNil(o.OperatingSystem) {
		var ret string
		return ret
	}
	return *o.OperatingSystem
}

// GetOperatingSystemOk returns a tuple with the OperatingSystem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedServer) GetOperatingSystemOk() (*string, bool) {
	if o == nil || IsNil(o.OperatingSystem) {
		return nil, false
	}
	return o.OperatingSystem, true
}

// HasOperatingSystem returns a boolean if a field has been set.
func (o *DedicatedServer) HasOperatingSystem() bool {
	if o != nil && !IsNil(o.OperatingSystem) {
		return true
	}

	return false
}

// SetOperatingSystem gets a reference to the given string and assigns it to the OperatingSystem field.
func (o *DedicatedServer) SetOperatingSystem(v string) {
	o.OperatingSystem = &v
}

// GetInstallOsOnHdd returns the InstallOsOnHdd field value if set, zero value otherwise.
func (o *DedicatedServer) GetInstallOsOnHdd() string {
	if o == nil || IsNil(o.InstallOsOnHdd) {
		var ret string
		return ret
	}
	return *o.InstallOsOnHdd
}

// GetInstallOsOnHddOk returns a tuple with the InstallOsOnHdd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedServer) GetInstallOsOnHddOk() (*string, bool) {
	if o == nil || IsNil(o.InstallOsOnHdd) {
		return nil, false
	}
	return o.InstallOsOnHdd, true
}

// HasInstallOsOnHdd returns a boolean if a field has been set.
func (o *DedicatedServer) HasInstallOsOnHdd() bool {
	if o != nil && !IsNil(o.InstallOsOnHdd) {
		return true
	}

	return false
}

// SetInstallOsOnHdd gets a reference to the given string and assigns it to the InstallOsOnHdd field.
func (o *DedicatedServer) SetInstallOsOnHdd(v string) {
	o.InstallOsOnHdd = &v
}

// GetControlPanel returns the ControlPanel field value if set, zero value otherwise.
func (o *DedicatedServer) GetControlPanel() string {
	if o == nil || IsNil(o.ControlPanel) {
		var ret string
		return ret
	}
	return *o.ControlPanel
}

// GetControlPanelOk returns a tuple with the ControlPanel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedServer) GetControlPanelOk() (*string, bool) {
	if o == nil || IsNil(o.ControlPanel) {
		return nil, false
	}
	return o.ControlPanel, true
}

// HasControlPanel returns a boolean if a field has been set.
func (o *DedicatedServer) HasControlPanel() bool {
	if o != nil && !IsNil(o.ControlPanel) {
		return true
	}

	return false
}

// SetControlPanel gets a reference to the given string and assigns it to the ControlPanel field.
func (o *DedicatedServer) SetControlPanel(v string) {
	o.ControlPanel = &v
}

// GetIpConnectivityType returns the IpConnectivityType field value if set, zero value otherwise.
func (o *DedicatedServer) GetIpConnectivityType() string {
	if o == nil || IsNil(o.IpConnectivityType) {
		var ret string
		return ret
	}
	return *o.IpConnectivityType
}

// GetIpConnectivityTypeOk returns a tuple with the IpConnectivityType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedServer) GetIpConnectivityTypeOk() (*string, bool) {
	if o == nil || IsNil(o.IpConnectivityType) {
		return nil, false
	}
	return o.IpConnectivityType, true
}

// HasIpConnectivityType returns a boolean if a field has been set.
func (o *DedicatedServer) HasIpConnectivityType() bool {
	if o != nil && !IsNil(o.IpConnectivityType) {
		return true
	}

	return false
}

// SetIpConnectivityType gets a reference to the given string and assigns it to the IpConnectivityType field.
func (o *DedicatedServer) SetIpConnectivityType(v string) {
	o.IpConnectivityType = &v
}

// GetDataPackConfiguration returns the DataPackConfiguration field value if set, zero value otherwise.
func (o *DedicatedServer) GetDataPackConfiguration() string {
	if o == nil || IsNil(o.DataPackConfiguration) {
		var ret string
		return ret
	}
	return *o.DataPackConfiguration
}

// GetDataPackConfigurationOk returns a tuple with the DataPackConfiguration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedServer) GetDataPackConfigurationOk() (*string, bool) {
	if o == nil || IsNil(o.DataPackConfiguration) {
		return nil, false
	}
	return o.DataPackConfiguration, true
}

// HasDataPackConfiguration returns a boolean if a field has been set.
func (o *DedicatedServer) HasDataPackConfiguration() bool {
	if o != nil && !IsNil(o.DataPackConfiguration) {
		return true
	}

	return false
}

// SetDataPackConfiguration gets a reference to the given string and assigns it to the DataPackConfiguration field.
func (o *DedicatedServer) SetDataPackConfiguration(v string) {
	o.DataPackConfiguration = &v
}

// GetUplinkPortSpeed returns the UplinkPortSpeed field value if set, zero value otherwise.
func (o *DedicatedServer) GetUplinkPortSpeed() string {
	if o == nil || IsNil(o.UplinkPortSpeed) {
		var ret string
		return ret
	}
	return *o.UplinkPortSpeed
}

// GetUplinkPortSpeedOk returns a tuple with the UplinkPortSpeed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedServer) GetUplinkPortSpeedOk() (*string, bool) {
	if o == nil || IsNil(o.UplinkPortSpeed) {
		return nil, false
	}
	return o.UplinkPortSpeed, true
}

// HasUplinkPortSpeed returns a boolean if a field has been set.
func (o *DedicatedServer) HasUplinkPortSpeed() bool {
	if o != nil && !IsNil(o.UplinkPortSpeed) {
		return true
	}

	return false
}

// SetUplinkPortSpeed gets a reference to the given string and assigns it to the UplinkPortSpeed field.
func (o *DedicatedServer) SetUplinkPortSpeed(v string) {
	o.UplinkPortSpeed = &v
}

// GetPrivateNetwork1xvlan returns the PrivateNetwork1xvlan field value if set, zero value otherwise.
func (o *DedicatedServer) GetPrivateNetwork1xvlan() string {
	if o == nil || IsNil(o.PrivateNetwork1xvlan) {
		var ret string
		return ret
	}
	return *o.PrivateNetwork1xvlan
}

// GetPrivateNetwork1xvlanOk returns a tuple with the PrivateNetwork1xvlan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedServer) GetPrivateNetwork1xvlanOk() (*string, bool) {
	if o == nil || IsNil(o.PrivateNetwork1xvlan) {
		return nil, false
	}
	return o.PrivateNetwork1xvlan, true
}

// HasPrivateNetwork1xvlan returns a boolean if a field has been set.
func (o *DedicatedServer) HasPrivateNetwork1xvlan() bool {
	if o != nil && !IsNil(o.PrivateNetwork1xvlan) {
		return true
	}

	return false
}

// SetPrivateNetwork1xvlan gets a reference to the given string and assigns it to the PrivateNetwork1xvlan field.
func (o *DedicatedServer) SetPrivateNetwork1xvlan(v string) {
	o.PrivateNetwork1xvlan = &v
}

// GetIpV4Configuration returns the IpV4Configuration field value if set, zero value otherwise.
func (o *DedicatedServer) GetIpV4Configuration() string {
	if o == nil || IsNil(o.IpV4Configuration) {
		var ret string
		return ret
	}
	return *o.IpV4Configuration
}

// GetIpV4ConfigurationOk returns a tuple with the IpV4Configuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedServer) GetIpV4ConfigurationOk() (*string, bool) {
	if o == nil || IsNil(o.IpV4Configuration) {
		return nil, false
	}
	return o.IpV4Configuration, true
}

// HasIpV4Configuration returns a boolean if a field has been set.
func (o *DedicatedServer) HasIpV4Configuration() bool {
	if o != nil && !IsNil(o.IpV4Configuration) {
		return true
	}

	return false
}

// SetIpV4Configuration gets a reference to the given string and assigns it to the IpV4Configuration field.
func (o *DedicatedServer) SetIpV4Configuration(v string) {
	o.IpV4Configuration = &v
}

// GetAdditionalServices returns the AdditionalServices field value if set, zero value otherwise.
func (o *DedicatedServer) GetAdditionalServices() []string {
	if o == nil || IsNil(o.AdditionalServices) {
		var ret []string
		return ret
	}
	return o.AdditionalServices
}

// GetAdditionalServicesOk returns a tuple with the AdditionalServices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedServer) GetAdditionalServicesOk() ([]string, bool) {
	if o == nil || IsNil(o.AdditionalServices) {
		return nil, false
	}
	return o.AdditionalServices, true
}

// HasAdditionalServices returns a boolean if a field has been set.
func (o *DedicatedServer) HasAdditionalServices() bool {
	if o != nil && !IsNil(o.AdditionalServices) {
		return true
	}

	return false
}

// SetAdditionalServices gets a reference to the given []string and assigns it to the AdditionalServices field.
func (o *DedicatedServer) SetAdditionalServices(v []string) {
	o.AdditionalServices = v
}

// GetMonitoringType returns the MonitoringType field value if set, zero value otherwise.
func (o *DedicatedServer) GetMonitoringType() string {
	if o == nil || IsNil(o.MonitoringType) {
		var ret string
		return ret
	}
	return *o.MonitoringType
}

// GetMonitoringTypeOk returns a tuple with the MonitoringType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedServer) GetMonitoringTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MonitoringType) {
		return nil, false
	}
	return o.MonitoringType, true
}

// HasMonitoringType returns a boolean if a field has been set.
func (o *DedicatedServer) HasMonitoringType() bool {
	if o != nil && !IsNil(o.MonitoringType) {
		return true
	}

	return false
}

// SetMonitoringType gets a reference to the given string and assigns it to the MonitoringType field.
func (o *DedicatedServer) SetMonitoringType(v string) {
	o.MonitoringType = &v
}

// GetDdosIpProtection returns the DdosIpProtection field value if set, zero value otherwise.
func (o *DedicatedServer) GetDdosIpProtection() string {
	if o == nil || IsNil(o.DdosIpProtection) {
		var ret string
		return ret
	}
	return *o.DdosIpProtection
}

// GetDdosIpProtectionOk returns a tuple with the DdosIpProtection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedServer) GetDdosIpProtectionOk() (*string, bool) {
	if o == nil || IsNil(o.DdosIpProtection) {
		return nil, false
	}
	return o.DdosIpProtection, true
}

// HasDdosIpProtection returns a boolean if a field has been set.
func (o *DedicatedServer) HasDdosIpProtection() bool {
	if o != nil && !IsNil(o.DdosIpProtection) {
		return true
	}

	return false
}

// SetDdosIpProtection gets a reference to the given string and assigns it to the DdosIpProtection field.
func (o *DedicatedServer) SetDdosIpProtection(v string) {
	o.DdosIpProtection = &v
}

// GetServiceLevelAgreement returns the ServiceLevelAgreement field value if set, zero value otherwise.
func (o *DedicatedServer) GetServiceLevelAgreement() string {
	if o == nil || IsNil(o.ServiceLevelAgreement) {
		var ret string
		return ret
	}
	return *o.ServiceLevelAgreement
}

// GetServiceLevelAgreementOk returns a tuple with the ServiceLevelAgreement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedServer) GetServiceLevelAgreementOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceLevelAgreement) {
		return nil, false
	}
	return o.ServiceLevelAgreement, true
}

// HasServiceLevelAgreement returns a boolean if a field has been set.
func (o *DedicatedServer) HasServiceLevelAgreement() bool {
	if o != nil && !IsNil(o.ServiceLevelAgreement) {
		return true
	}

	return false
}

// SetServiceLevelAgreement gets a reference to the given string and assigns it to the ServiceLevelAgreement field.
func (o *DedicatedServer) SetServiceLevelAgreement(v string) {
	o.ServiceLevelAgreement = &v
}

// GetConfigurationOptions returns the ConfigurationOptions field value if set, zero value otherwise.
func (o *DedicatedServer) GetConfigurationOptions() DedicatedServerConfigurationOptions1 {
	if o == nil || IsNil(o.ConfigurationOptions) {
		var ret DedicatedServerConfigurationOptions1
		return ret
	}
	return *o.ConfigurationOptions
}

// GetConfigurationOptionsOk returns a tuple with the ConfigurationOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedServer) GetConfigurationOptionsOk() (*DedicatedServerConfigurationOptions1, bool) {
	if o == nil || IsNil(o.ConfigurationOptions) {
		return nil, false
	}
	return o.ConfigurationOptions, true
}

// HasConfigurationOptions returns a boolean if a field has been set.
func (o *DedicatedServer) HasConfigurationOptions() bool {
	if o != nil && !IsNil(o.ConfigurationOptions) {
		return true
	}

	return false
}

// SetConfigurationOptions gets a reference to the given DedicatedServerConfigurationOptions1 and assigns it to the ConfigurationOptions field.
func (o *DedicatedServer) SetConfigurationOptions(v DedicatedServerConfigurationOptions1) {
	o.ConfigurationOptions = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *DedicatedServer) GetPrice() ProductPricePrice {
	if o == nil || IsNil(o.Price) {
		var ret ProductPricePrice
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DedicatedServer) GetPriceOk() (*ProductPricePrice, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *DedicatedServer) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given ProductPricePrice and assigns it to the Price field.
func (o *DedicatedServer) SetPrice(v ProductPricePrice) {
	o.Price = &v
}

func (o DedicatedServer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DedicatedServer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Chassis) {
		toSerialize["chassis"] = o.Chassis
	}
	if !IsNil(o.Cpu) {
		toSerialize["cpu"] = o.Cpu
	}
	if !IsNil(o.DeliveryMethod) {
		toSerialize["deliveryMethod"] = o.DeliveryMethod
	}
	if !IsNil(o.Hdd) {
		toSerialize["hdd"] = o.Hdd
	}
	if !IsNil(o.Ram) {
		toSerialize["ram"] = o.Ram
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.OperatingSystem) {
		toSerialize["operatingSystem"] = o.OperatingSystem
	}
	if !IsNil(o.InstallOsOnHdd) {
		toSerialize["installOsOnHdd"] = o.InstallOsOnHdd
	}
	if !IsNil(o.ControlPanel) {
		toSerialize["controlPanel"] = o.ControlPanel
	}
	if !IsNil(o.IpConnectivityType) {
		toSerialize["ipConnectivityType"] = o.IpConnectivityType
	}
	if !IsNil(o.DataPackConfiguration) {
		toSerialize["dataPackConfiguration"] = o.DataPackConfiguration
	}
	if !IsNil(o.UplinkPortSpeed) {
		toSerialize["uplinkPortSpeed"] = o.UplinkPortSpeed
	}
	if !IsNil(o.PrivateNetwork1xvlan) {
		toSerialize["privateNetwork1xvlan"] = o.PrivateNetwork1xvlan
	}
	if !IsNil(o.IpV4Configuration) {
		toSerialize["ipV4Configuration"] = o.IpV4Configuration
	}
	if !IsNil(o.AdditionalServices) {
		toSerialize["additionalServices"] = o.AdditionalServices
	}
	if !IsNil(o.MonitoringType) {
		toSerialize["monitoringType"] = o.MonitoringType
	}
	if !IsNil(o.DdosIpProtection) {
		toSerialize["ddosIpProtection"] = o.DdosIpProtection
	}
	if !IsNil(o.ServiceLevelAgreement) {
		toSerialize["serviceLevelAgreement"] = o.ServiceLevelAgreement
	}
	if !IsNil(o.ConfigurationOptions) {
		toSerialize["configurationOptions"] = o.ConfigurationOptions
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DedicatedServer) UnmarshalJSON(data []byte) (err error) {
	varDedicatedServer := _DedicatedServer{}

	err = json.Unmarshal(data, &varDedicatedServer)

	if err != nil {
		return err
	}

	*o = DedicatedServer(varDedicatedServer)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "chassis")
		delete(additionalProperties, "cpu")
		delete(additionalProperties, "deliveryMethod")
		delete(additionalProperties, "hdd")
		delete(additionalProperties, "ram")
		delete(additionalProperties, "location")
		delete(additionalProperties, "operatingSystem")
		delete(additionalProperties, "installOsOnHdd")
		delete(additionalProperties, "controlPanel")
		delete(additionalProperties, "ipConnectivityType")
		delete(additionalProperties, "dataPackConfiguration")
		delete(additionalProperties, "uplinkPortSpeed")
		delete(additionalProperties, "privateNetwork1xvlan")
		delete(additionalProperties, "ipV4Configuration")
		delete(additionalProperties, "additionalServices")
		delete(additionalProperties, "monitoringType")
		delete(additionalProperties, "ddosIpProtection")
		delete(additionalProperties, "serviceLevelAgreement")
		delete(additionalProperties, "configurationOptions")
		delete(additionalProperties, "price")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDedicatedServer struct {
	value *DedicatedServer
	isSet bool
}

func (v NullableDedicatedServer) Get() *DedicatedServer {
	return v.value
}

func (v *NullableDedicatedServer) Set(val *DedicatedServer) {
	v.value = val
	v.isSet = true
}

func (v NullableDedicatedServer) IsSet() bool {
	return v.isSet
}

func (v *NullableDedicatedServer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDedicatedServer(val *DedicatedServer) *NullableDedicatedServer {
	return &NullableDedicatedServer{value: val, isSet: true}
}

func (v NullableDedicatedServer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDedicatedServer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


