/*
Ordering

This document outlines the ordering API. The API is only available for customers with invoice payment method.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ordering

import (
	"encoding/json"
	"fmt"
)

// checks if the OrderVpsOpts type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderVpsOpts{}

// OrderVpsOpts struct for OrderVpsOpts
type OrderVpsOpts struct {
	// The datacenter location
	Location string `json:"location"`
	// Disk upgrade option
	DiskUpgrade *string `json:"diskUpgrade,omitempty"`
	// Operating system option
	OperatingSystem *string `json:"operatingSystem,omitempty"`
	// Control panel option
	ControlPanel *string `json:"controlPanel,omitempty"`
	ServiceLevelAgreement *ServiceLevelAgreement `json:"serviceLevelAgreement,omitempty"`
	ContractTerm *ContractTerm `json:"contractTerm,omitempty"`
	BillingCycle *BillingCycle `json:"billingCycle,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OrderVpsOpts OrderVpsOpts

// NewOrderVpsOpts instantiates a new OrderVpsOpts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderVpsOpts(location string) *OrderVpsOpts {
	this := OrderVpsOpts{}
	this.Location = location
	var contractTerm ContractTerm = CONTRACTTERM__1_YEAR
	this.ContractTerm = &contractTerm
	var billingCycle BillingCycle = BILLINGCYCLE__1_MONTH
	this.BillingCycle = &billingCycle
	return &this
}

// NewOrderVpsOptsWithDefaults instantiates a new OrderVpsOpts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderVpsOptsWithDefaults() *OrderVpsOpts {
	this := OrderVpsOpts{}
	var contractTerm ContractTerm = CONTRACTTERM__1_YEAR
	this.ContractTerm = &contractTerm
	var billingCycle BillingCycle = BILLINGCYCLE__1_MONTH
	this.BillingCycle = &billingCycle
	return &this
}

// GetLocation returns the Location field value
func (o *OrderVpsOpts) GetLocation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Location
}

// GetLocationOk returns a tuple with the Location field value
// and a boolean to check if the value has been set.
func (o *OrderVpsOpts) GetLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Location, true
}

// SetLocation sets field value
func (o *OrderVpsOpts) SetLocation(v string) {
	o.Location = v
}

// GetDiskUpgrade returns the DiskUpgrade field value if set, zero value otherwise.
func (o *OrderVpsOpts) GetDiskUpgrade() string {
	if o == nil || IsNil(o.DiskUpgrade) {
		var ret string
		return ret
	}
	return *o.DiskUpgrade
}

// GetDiskUpgradeOk returns a tuple with the DiskUpgrade field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderVpsOpts) GetDiskUpgradeOk() (*string, bool) {
	if o == nil || IsNil(o.DiskUpgrade) {
		return nil, false
	}
	return o.DiskUpgrade, true
}

// HasDiskUpgrade returns a boolean if a field has been set.
func (o *OrderVpsOpts) HasDiskUpgrade() bool {
	if o != nil && !IsNil(o.DiskUpgrade) {
		return true
	}

	return false
}

// SetDiskUpgrade gets a reference to the given string and assigns it to the DiskUpgrade field.
func (o *OrderVpsOpts) SetDiskUpgrade(v string) {
	o.DiskUpgrade = &v
}

// GetOperatingSystem returns the OperatingSystem field value if set, zero value otherwise.
func (o *OrderVpsOpts) GetOperatingSystem() string {
	if o == nil || IsNil(o.OperatingSystem) {
		var ret string
		return ret
	}
	return *o.OperatingSystem
}

// GetOperatingSystemOk returns a tuple with the OperatingSystem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderVpsOpts) GetOperatingSystemOk() (*string, bool) {
	if o == nil || IsNil(o.OperatingSystem) {
		return nil, false
	}
	return o.OperatingSystem, true
}

// HasOperatingSystem returns a boolean if a field has been set.
func (o *OrderVpsOpts) HasOperatingSystem() bool {
	if o != nil && !IsNil(o.OperatingSystem) {
		return true
	}

	return false
}

// SetOperatingSystem gets a reference to the given string and assigns it to the OperatingSystem field.
func (o *OrderVpsOpts) SetOperatingSystem(v string) {
	o.OperatingSystem = &v
}

// GetControlPanel returns the ControlPanel field value if set, zero value otherwise.
func (o *OrderVpsOpts) GetControlPanel() string {
	if o == nil || IsNil(o.ControlPanel) {
		var ret string
		return ret
	}
	return *o.ControlPanel
}

// GetControlPanelOk returns a tuple with the ControlPanel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderVpsOpts) GetControlPanelOk() (*string, bool) {
	if o == nil || IsNil(o.ControlPanel) {
		return nil, false
	}
	return o.ControlPanel, true
}

// HasControlPanel returns a boolean if a field has been set.
func (o *OrderVpsOpts) HasControlPanel() bool {
	if o != nil && !IsNil(o.ControlPanel) {
		return true
	}

	return false
}

// SetControlPanel gets a reference to the given string and assigns it to the ControlPanel field.
func (o *OrderVpsOpts) SetControlPanel(v string) {
	o.ControlPanel = &v
}

// GetServiceLevelAgreement returns the ServiceLevelAgreement field value if set, zero value otherwise.
func (o *OrderVpsOpts) GetServiceLevelAgreement() ServiceLevelAgreement {
	if o == nil || IsNil(o.ServiceLevelAgreement) {
		var ret ServiceLevelAgreement
		return ret
	}
	return *o.ServiceLevelAgreement
}

// GetServiceLevelAgreementOk returns a tuple with the ServiceLevelAgreement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderVpsOpts) GetServiceLevelAgreementOk() (*ServiceLevelAgreement, bool) {
	if o == nil || IsNil(o.ServiceLevelAgreement) {
		return nil, false
	}
	return o.ServiceLevelAgreement, true
}

// HasServiceLevelAgreement returns a boolean if a field has been set.
func (o *OrderVpsOpts) HasServiceLevelAgreement() bool {
	if o != nil && !IsNil(o.ServiceLevelAgreement) {
		return true
	}

	return false
}

// SetServiceLevelAgreement gets a reference to the given ServiceLevelAgreement and assigns it to the ServiceLevelAgreement field.
func (o *OrderVpsOpts) SetServiceLevelAgreement(v ServiceLevelAgreement) {
	o.ServiceLevelAgreement = &v
}

// GetContractTerm returns the ContractTerm field value if set, zero value otherwise.
func (o *OrderVpsOpts) GetContractTerm() ContractTerm {
	if o == nil || IsNil(o.ContractTerm) {
		var ret ContractTerm
		return ret
	}
	return *o.ContractTerm
}

// GetContractTermOk returns a tuple with the ContractTerm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderVpsOpts) GetContractTermOk() (*ContractTerm, bool) {
	if o == nil || IsNil(o.ContractTerm) {
		return nil, false
	}
	return o.ContractTerm, true
}

// HasContractTerm returns a boolean if a field has been set.
func (o *OrderVpsOpts) HasContractTerm() bool {
	if o != nil && !IsNil(o.ContractTerm) {
		return true
	}

	return false
}

// SetContractTerm gets a reference to the given ContractTerm and assigns it to the ContractTerm field.
func (o *OrderVpsOpts) SetContractTerm(v ContractTerm) {
	o.ContractTerm = &v
}

// GetBillingCycle returns the BillingCycle field value if set, zero value otherwise.
func (o *OrderVpsOpts) GetBillingCycle() BillingCycle {
	if o == nil || IsNil(o.BillingCycle) {
		var ret BillingCycle
		return ret
	}
	return *o.BillingCycle
}

// GetBillingCycleOk returns a tuple with the BillingCycle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderVpsOpts) GetBillingCycleOk() (*BillingCycle, bool) {
	if o == nil || IsNil(o.BillingCycle) {
		return nil, false
	}
	return o.BillingCycle, true
}

// HasBillingCycle returns a boolean if a field has been set.
func (o *OrderVpsOpts) HasBillingCycle() bool {
	if o != nil && !IsNil(o.BillingCycle) {
		return true
	}

	return false
}

// SetBillingCycle gets a reference to the given BillingCycle and assigns it to the BillingCycle field.
func (o *OrderVpsOpts) SetBillingCycle(v BillingCycle) {
	o.BillingCycle = &v
}

func (o OrderVpsOpts) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderVpsOpts) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["location"] = o.Location
	if !IsNil(o.DiskUpgrade) {
		toSerialize["diskUpgrade"] = o.DiskUpgrade
	}
	if !IsNil(o.OperatingSystem) {
		toSerialize["operatingSystem"] = o.OperatingSystem
	}
	if !IsNil(o.ControlPanel) {
		toSerialize["controlPanel"] = o.ControlPanel
	}
	if !IsNil(o.ServiceLevelAgreement) {
		toSerialize["serviceLevelAgreement"] = o.ServiceLevelAgreement
	}
	if !IsNil(o.ContractTerm) {
		toSerialize["contractTerm"] = o.ContractTerm
	}
	if !IsNil(o.BillingCycle) {
		toSerialize["billingCycle"] = o.BillingCycle
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OrderVpsOpts) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"location",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrderVpsOpts := _OrderVpsOpts{}

	err = json.Unmarshal(data, &varOrderVpsOpts)

	if err != nil {
		return err
	}

	*o = OrderVpsOpts(varOrderVpsOpts)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "location")
		delete(additionalProperties, "diskUpgrade")
		delete(additionalProperties, "operatingSystem")
		delete(additionalProperties, "controlPanel")
		delete(additionalProperties, "serviceLevelAgreement")
		delete(additionalProperties, "contractTerm")
		delete(additionalProperties, "billingCycle")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOrderVpsOpts struct {
	value *OrderVpsOpts
	isSet bool
}

func (v NullableOrderVpsOpts) Get() *OrderVpsOpts {
	return v.value
}

func (v *NullableOrderVpsOpts) Set(val *OrderVpsOpts) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderVpsOpts) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderVpsOpts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderVpsOpts(val *OrderVpsOpts) *NullableOrderVpsOpts {
	return &NullableOrderVpsOpts{value: val, isSet: true}
}

func (v NullableOrderVpsOpts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderVpsOpts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


