/*
Leaseweb API for dedicated servers

This documents the rest api dedicatedserver provides.

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dedicatedserver

import (
	"encoding/json"
	"fmt"
)

// checks if the ControlPanel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ControlPanel{}

// ControlPanel A single control panel
type ControlPanel struct {
	// The unique ID of this control panel
	Id string `json:"id"`
	// A human readable name describing the control panel
	Name string `json:"name"`
	AdditionalProperties map[string]interface{}
}

type _ControlPanel ControlPanel

// NewControlPanel instantiates a new ControlPanel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewControlPanel(id string, name string) *ControlPanel {
	this := ControlPanel{}
	this.Id = id
	this.Name = name
	return &this
}

// NewControlPanelWithDefaults instantiates a new ControlPanel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewControlPanelWithDefaults() *ControlPanel {
	this := ControlPanel{}
	return &this
}

// GetId returns the Id field value
func (o *ControlPanel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ControlPanel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ControlPanel) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ControlPanel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ControlPanel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ControlPanel) SetName(v string) {
	o.Name = v
}

func (o ControlPanel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ControlPanel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ControlPanel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varControlPanel := _ControlPanel{}

	err = json.Unmarshal(data, &varControlPanel)

	if err != nil {
		return err
	}

	*o = ControlPanel(varControlPanel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableControlPanel struct {
	value *ControlPanel
	isSet bool
}

func (v NullableControlPanel) Get() *ControlPanel {
	return v.value
}

func (v *NullableControlPanel) Set(val *ControlPanel) {
	v.value = val
	v.isSet = true
}

func (v NullableControlPanel) IsSet() bool {
	return v.isSet
}

func (v *NullableControlPanel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableControlPanel(val *ControlPanel) *NullableControlPanel {
	return &NullableControlPanel{value: val, isSet: true}
}

func (v NullableControlPanel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableControlPanel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


