/*
Dedicated Servers

This is the description of the Dedicated Server API.  The base url of this API is `https://api.leaseweb.com`.

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dedicatedserver

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// CpuFreq - struct for CpuFreq
type CpuFreq struct {
	Bool *bool
	String *string
}

// boolAsCpuFreq is a convenience function that returns bool wrapped in CpuFreq
func BoolAsCpuFreq(v *bool) CpuFreq {
	return CpuFreq{
		Bool: v,
	}
}

// stringAsCpuFreq is a convenience function that returns string wrapped in CpuFreq
func StringAsCpuFreq(v *string) CpuFreq {
	return CpuFreq{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CpuFreq) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Bool
	err = newStrictDecoder(data).Decode(&dst.Bool)
	if err == nil {
		jsonBool, _ := json.Marshal(dst.Bool)
		if string(jsonBool) == "{}" { // empty struct
			dst.Bool = nil
		} else {
			if err = validator.Validate(dst.Bool); err != nil {
				dst.Bool = nil
			} else {
				match++
			}
		}
	} else {
		dst.Bool = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Bool = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CpuFreq)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CpuFreq)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CpuFreq) MarshalJSON() ([]byte, error) {
	if src.Bool != nil {
		return json.Marshal(&src.Bool)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CpuFreq) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Bool != nil {
		return obj.Bool
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableCpuFreq struct {
	value *CpuFreq
	isSet bool
}

func (v NullableCpuFreq) Get() *CpuFreq {
	return v.value
}

func (v *NullableCpuFreq) Set(val *CpuFreq) {
	v.value = val
	v.isSet = true
}

func (v NullableCpuFreq) IsSet() bool {
	return v.isSet
}

func (v *NullableCpuFreq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCpuFreq(val *CpuFreq) *NullableCpuFreq {
	return &NullableCpuFreq{value: val, isSet: true}
}

func (v NullableCpuFreq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCpuFreq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


