/*
Leaseweb API for dedicated servers

This documents the rest api dedicatedserver provides.

API version: v2
Contact: development-networkautomation@leaseweb.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dedicatedServer

import (
	"encoding/json"
)

// checks if the HardwareScanDisk type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HardwareScanDisk{}

// HardwareScanDisk struct for HardwareScanDisk
type HardwareScanDisk struct {
	Description *string `json:"description,omitempty"`
	Id *string `json:"id,omitempty"`
}

// NewHardwareScanDisk instantiates a new HardwareScanDisk object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHardwareScanDisk() *HardwareScanDisk {
	this := HardwareScanDisk{}
	return &this
}

// NewHardwareScanDiskWithDefaults instantiates a new HardwareScanDisk object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHardwareScanDiskWithDefaults() *HardwareScanDisk {
	this := HardwareScanDisk{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *HardwareScanDisk) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HardwareScanDisk) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *HardwareScanDisk) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *HardwareScanDisk) SetDescription(v string) {
	o.Description = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *HardwareScanDisk) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HardwareScanDisk) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *HardwareScanDisk) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *HardwareScanDisk) SetId(v string) {
	o.Id = &v
}

func (o HardwareScanDisk) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HardwareScanDisk) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableHardwareScanDisk struct {
	value *HardwareScanDisk
	isSet bool
}

func (v NullableHardwareScanDisk) Get() *HardwareScanDisk {
	return v.value
}

func (v *NullableHardwareScanDisk) Set(val *HardwareScanDisk) {
	v.value = val
	v.isSet = true
}

func (v NullableHardwareScanDisk) IsSet() bool {
	return v.isSet
}

func (v *NullableHardwareScanDisk) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHardwareScanDisk(val *HardwareScanDisk) *NullableHardwareScanDisk {
	return &NullableHardwareScanDisk{value: val, isSet: true}
}

func (v NullableHardwareScanDisk) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHardwareScanDisk) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


