name: Go

on:
  push:
    branches: [ "master", "feature/terraform-endpoints" ]
  pull_request:
    branches: [ "master", "feature/terraform-endpoints" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.2

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
